export enum EdgeType {
  BELONGS_TO = 'BELONGS_TO',
  IMPLEMENTS = 'IMPLEMENTS',
  EXTENDS = 'EXTENDS',
  IMPORTS = 'IMPORTS',
  DEPENDS_ON = 'DEPENDS_ON',
  EXPOSES = 'EXPOSES',
  PROTECTS = 'PROTECTS',
  TRANSFORMS = 'TRANSFORMS',
}
