export enum NodeType {
  PROJECT = 'Project',
  PACKAGE = 'Package',
  MODULE = 'Module',
  CONTROLLER = 'Controller',
  SERVICE = 'Service',
  REPOSITORY = 'Repository',
  ENTITY = 'Entity',
  DTO = 'DTO',
  INTERFACE = 'Interface',
  ENDPOINT = 'Endpoint',
  EXTERNAL_DEPENDENCY = 'ExternalDependency',
  GUARD = 'Guard',
  PIPE = 'Pipe',
  INTERCEPTOR = 'Interceptor',
  MIDDLEWARE = 'Middleware',
  UNKNOWN = 'Unknown',
}
